Primeiro Cartão
geovaniggr/livraria-edigi pull request #1
Opened 2020-04-28 14:30 UTC by geovaniggr

Opa wuands, para não inflar de `mains` na parte de testes eu optei por colocar vários `try-catch` e manter só um arquivo enquanto não é para utilizar as bibliotecas de testes, tudo bem?

2020-04-28 16:27 UTC, wandersonmaceds requested changes
Gostei da ideia dos try/catch, vai facilitar bastante para quando você for transformar isso em testes de verdade. 

Aqui, no geral, acredito que vieram os padrões de codificação do mundo js, o que não é um problema, mas pode tornar a leitura do código difícil para quem está acostumando com o ecossistema Java.

2020-04-28 16:27 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/model/Author.java
> +    private LocalDateTime created_at;
No Java é menos comum você usar snake_case, use camelCase só para manter o padrão de estilo recomendado para a linguagem :)

2020-04-28 16:27 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/model/Author.java
> +        if(isNull(name)) throw new IllegalArgumentException("O nome não pode ser vazio");
O seu isNull não verifica por nulidade, mas sim por string vazia. 

No Java, é menos comum você isolar essas validações mais simples, aqui, traria sim o isEmpty e o fazer o `== null` diretamente no método.

2020-04-28 16:27 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/validators/ValidationUtils.java
> +package br.com.alura.edigi.validators;
Acho que é prematuro criar essa classe e esse pacote nesse estágio.

2020-04-28 16:27 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/repository/AuthorRepository.java
> +public class AuthorRepository {
Se a lista não permite replicação, talvez vala a pena usar uma coleção que já trate desse tipo de questão. O hasAuthor, no contexto atual, é totalmente descartável, visto que o add do ArrayList pode te retornar um boleano.

2020-04-28 22:23 UTC, geovaniggr commented on src/main/java/br/com/alura/edigi/model/Author.java
> +    private LocalDateTime created_at;
Realmente, isso foi um pequeno vicio de utilizar o sequelize para não dar conflito com o banco de dados

2020-04-29 12:08 UTC, wandersonmaceds approved these changes
Boa! 

Sobre a nomenclatura dos pacotes, é mais comum que sigam o mesmo padrão das classes, porem, em lowercase, eu não birro com isso, escolha um padrão e siga. Eu chamaria de model e repository, apesar de ser convenção que um pacote guarda mais que uma classe. É opção sua, mas o código pra mim está ok.

2020-04-29 17:05 UTC, merged