Entidade Livro
geovaniggr/livraria-edigi pull request #3
Opened 2020-05-08 13:11 UTC by geovaniggr

2020-05-08 22:52 UTC, wandersonmaceds requested changes
Mandou bem!

2020-05-08 22:52 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/model/Book.java
> +        if (synopsis.length() > 500)
Acho que aqui é o contrário não? precisa ter pelo menos 500 caracteres.

2020-05-08 22:52 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/model/Book.java
> +        if ( numberOfPages == null || numberOfPages.intValue() <= 0)
O número de páginas é maior que zero, sempre.

2020-05-08 22:52 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/model/Book.java
> +    public void setAuthor(Author author) {
se você recebe o autor via construtor, por que deixaria público a alteração do autor?

2020-05-08 22:52 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/model/Book.java
> +        return this.title.equals(other.title);
Se o ISBN também é único, adicionaria ele no equals :)

2020-05-08 22:52 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/controller/BookController.java
> +    }
Achei a abordagem interessante e perigosa, por que ao mesmo tempo que você confere a existência do autor e da categoria e se defende da não existência, você também acopla as entidades. Isso por que, se em algum momento, tivermos demais entidades envolvidas na criação do livro, você também precisará mexer neste código. 

O lado bom é que você já se defendeu das NPEs, por que há checagens de null em todos os possíveis lugares.

Consigo pensar em três abordagens:

1. Confiar que o livro vem preenchido corretamente e remover essas checagem do Author e Categoria. ou.
2. Fazer o cascading, se a categoria ou o autor não existem, salve os dois.
3. Deixar como está, assim você assegura que para criar um livro, o processo de criar a categoria e o author, precisam ser feitos antes. (prefiro, se manter a consistência em outros possíveis lugares)

2020-05-09 14:52 UTC, geovaniggr commented on src/main/java/br/com/alura/edigi/model/Book.java
> +        if ( numberOfPages == null || numberOfPages.intValue() <= 0)
Não entendi muito bem, pois a restrição era de que "precisa ser maior que zero", então compreendi que eu tinha que garantir que valores inválidos fossem barrados :thinking:

2020-05-09 14:55 UTC, geovaniggr commented on src/main/java/br/com/alura/edigi/controller/BookController.java
> +    }
Eu tinha pensado em fazer a segunda abordagem, mas não achei muito válido

3. Eu só não entendi a última parte de manter a consistência em outros lugares

2020-05-09 18:46 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/model/Book.java
> +        if ( numberOfPages == null || numberOfPages.intValue() <= 0)
Boa, precisa ser maior, então por que o zero seria aceito no if?

2020-05-09 18:47 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/controller/BookController.java
> +    }
Digo, se houver situações parecidas em que existe a dependência de uma entidade estar salva para poder salvar outra, você manter a mesma estratégia. Por que seria inconsistente que em um lugar você faça cascading e no outro não.

2020-05-15 17:36 UTC, geovaniggr commented on src/main/java/br/com/alura/edigi/model/Book.java
> +        if ( numberOfPages == null || numberOfPages.intValue() <= 0)
Então, mas a validação é do valor ser menor ou igual a 0, e caso positivo lançar a exceção, então na minha cabeça está correto 

Agora a mensagem eu concordo plenamente que estava errada / dúbia, pois aparentava poder inserir o valor 0

2020-05-15 19:04 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/model/Book.java
> +        if ( numberOfPages == null || numberOfPages.intValue() <= 0)
Na regra, o número de páginas deve ser maior que zero, ou seja, o zero não deve ser incluso.

2020-05-22 17:27 UTC, wandersonmaceds approved these changes

2020-05-23 15:33 UTC, merged