Entidade de Carrinho e Controle
geovaniggr/livraria-edigi pull request #5
Opened 2020-06-05 23:00 UTC by geovaniggr

Opa wanderson, fiz as alterações de retorno do book controller, apenas o checkout eu mantive como String pois não pensei um retorno melhor

2020-06-06 17:35 UTC, wandersonmaceds requested changes

2020-06-06 17:35 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/controller/BookController.java
> +        return book;
Vamos pensar um pouco aqui? Por que você devolveria o livro que você recebeu por parâmetro e não passou por nenhuma alteração? Acho que tem outra de você expressar o sucesso da operação ainda sim, imprimir a mensagem sem precisar retornar o livro que não passou por nenhuma mudança de estado.

2020-06-06 17:35 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/controller/BookController.java
> +            throw new IllegalArgumentException("Nenhum livro encontrado com essse título");
Acho que o caso é mais de runtime mesmo, Isso por que não é um caso de parâmetro inválido.

2020-06-06 17:35 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/controller/CartController.java
> +public class CartController {
Estou reflexivo sobre essa classe, ela não faz nada além de repassar chamadas. As demais estão bem modeladas, mas essa eu estou pensativo sobre a necessidade dela.

2020-06-17 12:16 UTC, wandersonmaceds requested changes

2020-06-17 12:16 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/model/Cart.java
>      }
Complexo, mas bonito e funcional. Mandou bem!
Eu só fico na dúvida se você precisa desse new BigDecimal ali já que a multiplicação é por um inteiro.

2020-06-17 12:16 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/model/Cart.java
>      }
Notei que esse new BigDecimal ali você faz em mais lugares, então por que não mudar o mapa para usar Book e BigDecimal direto?

2020-06-17 12:16 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/controller/BookController.java
> +        return true;
Aqui, me parece estranho uma condição disparar exception e a outra não, sendo que as duas validação o mesmo tipo de regra. 

Também parece que a illegal já não satisfaz a regra, não é mesmo? Não é uma invalidade do parâmetro, mas sim a inexistência do dado em tempo de execução.

2020-06-17 15:12 UTC, geovaniggr commented on src/main/java/br/com/alura/edigi/model/Cart.java
>      }
Então é que com o `BigDecimal` não é possível utilizar o operadores matemáticos, apenas as funções, e a de multiplicação espera como parâmetro um valor do tipo `BigDecimal`, então acaba tendo essa conversão "estranha" para manter o valor correto

Em relação a fazer um Map<Book, BigDecimal> acredito que gera um ruído, pois parece que a quantidade é um valor que pode ser algo "quebrado", e eu penso que se tivesse um método para pegar a quantidade de um livro ia ser um pouco estranho devolver um valor do tipo bigdecimal, sendo que com integer tem o unboxing automático

Eu também achei um pouco desconfortável, mas as duas vezes que eu utilizo essa forma é com a mesma motivação de obter o preço total de um item, algo que poderia diminuir um pouco seria criar uma função `calculateItemPrice` que limpasse um pouco essa lógica:

``` 
         return this.items.entrySet().stream()
                .map(item -> calculateItemPrice( item.getKey().getPrice(), item.getValue() ))
                .reduce(BigDecimal.ZERO, (previousValue, atualValue) -> previousValue.add(atualValue));


private BigDecimal calculateItemPrice( BigDecimal unityPrice, Integer quantity) {
     return  unityPrice.multiply( new BigDecimal(quantity) );
}
```

2020-06-17 15:14 UTC, geovaniggr commented on src/main/java/br/com/alura/edigi/controller/BookController.java
> +        return true;
Tem toda razão, tive o pensamento de o ser um input do usuário, ai faria sentido o IllegalArgument, masss uma runtime faz bem mais sentido

2020-06-18 14:09 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/model/Cart.java
>      }
São bons pontos, vamos deixar assim como está, no futuro talvez apareça uma forma mais simples de resolver isso.

2020-06-18 21:59 UTC, wandersonmaceds reviewed
Acho estranho que o seu test faça o throw, vamos fazer o seguinte, considerando o controller, vamos considerar ele void que pode disparar uma runtime, acho que é o melhor caminho por enquanto.

2020-06-22 20:40 UTC, wandersonmaceds approved these changes

2020-06-23 22:32 UTC, merged