add: Testes com Junit
geovaniggr/livraria-edigi pull request #6
Opened 2020-07-16 17:15 UTC by geovaniggr

Uma mudança que foi necessária foi trocar de `HashSet` para `ArrayList` no caso do `BookRepository` pois como são 2 informações conflituosas ( ISBN ou Nome), o Set não atende bem ao quesito pois ele trabalha apenas com informações iguais ( no caso teria que ser ISBN e Nome) pois ele só ira verificar o `equals` caso o `hashcode` seja igual ( quando há um conflito).

Neste caso se um autor tem mesmo ISBN porém nome diferentes, o hashcode gerado é diferente, então ao inserir não é gerado erro, pois em nenhum momento há conflito de espalhamento.

2020-07-28 12:29 UTC, wandersonmaceds commented
> Uma mudança que foi necessária foi trocar de `HashSet` para `ArrayList` no caso do `BookRepository` pois como são 2 informações conflituosas ( ISBN ou Nome), o Set não atende bem ao quesito pois ele trabalha apenas com informações iguais ( no caso teria que ser ISBN e Nome) pois ele só ira verificar o `equals` caso o `hashcode` seja igual ( quando há um conflito).
> 
> Neste caso se um autor tem mesmo ISBN porém nome diferentes, o hashcode gerado é diferente, então ao inserir não é gerado erro, pois em nenhum momento há conflito de espalhamento.

Então, mas no caso do Livro, se o ISBN for diferente, é correto dizer que é um outro livro, assim como se o nome for outro. Até onde sei, você não pode ter dois livros com o mesmo ISBN e nomes diferentes. Acho que tá correto.

2020-07-28 13:01 UTC, wandersonmaceds requested changes
Falando em testes em si, acredito ser confuso ver asserts no mesmo teste que verifiquem lógicas do tipo OU. Algo em mim diz que se forem lógicas do tipo OU, isso deve ser traduzido para testes diferentes. Claro, lógicas do tipo E são mais fáceis de se agrupar em um mesmo teste, mas há a questão mais abstrata. Podem haver lógicas do tipo E que são agrupadas que estão dentro de contextos do tipo OU, sendo assim, você teria testes E agrupados dentro de contextos OU. 

Um exemplo direto é: 
> Dado um nível de usuário (admin OU não), ele deve ter acessos a esse grupo de recursos (E).

No nosso caso, podemos trazer esse exemplo para o Livro: 
> Um livro é igual a outro se seu título E ISBN forem iguais OU seus autores forem diferentes.

Claro a regra de igualdade dos livros foi simplificada no projeto, mas usei isso como exemplo para você ver se por acaso algum agrupamento de testes escritos aqui, não se encaixam em uma reflexão parecida.

Veja se faz sentido.

2020-07-28 13:01 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/model/Book.java
> -    }
Aqui você poderia só ter trocado a implementação para resolver o problema que você detectou, se o equals mudou, mudar o hashcode também, não simplesmente jogar ele fora e com isso jogar fora o benefício do set também.

2020-07-28 13:01 UTC, wandersonmaceds commented on src/test/java/br/com/alura/edigi/controller/BookControllerTest.java
> +    }
Acredito que cada teste de unidade, deve garantir uma regra, não duas.

2020-07-28 13:01 UTC, wandersonmaceds commented on src/test/java/br/com/alura/edigi/controller/BookControllerTest.java
> +    }
Aqui não vi o benefício de ter criado um autor estático se na prática, você também instância outro autor na mão.

2020-07-28 13:01 UTC, wandersonmaceds commented on src/test/java/br/com/alura/edigi/controller/BookControllerTest.java
> +    }
Aqui não tem assert? Algo da JUnit assume que esse teste vai passar sem assert?

2020-07-28 13:01 UTC, wandersonmaceds commented on src/test/java/br/com/alura/edigi/models/AuthorTest.java
> +    @DisplayName("Autor com dados vazios ou nulos não deve ser criado")
A interpretação desse caso de teste tem muitos "ous": nome ou email não pode ser nulo ou vazio.

2020-07-28 13:01 UTC, wandersonmaceds commented on src/test/java/br/com/alura/edigi/respository/AuthorRepositoryTest.java
> +        System.out.println(author);
Aqui cê não precisa disso né? Não tem assert mesmo?

2020-07-28 13:01 UTC, wandersonmaceds commented on src/test/java/br/com/alura/edigi/models/BookTest.java
> +    @DisplayName("Criação de livro com algum campo nulo deve lançar exceção")
É confuso ver que não tem uma consistência, em algum lugar você diz que algo não deve ser criado quando vier dado inválido, aqui você diz que vai lançar exception, acho bom manter um padrão.

2020-08-26 19:09 UTC, geovaniggr commented on src/test/java/br/com/alura/edigi/controller/BookControllerTest.java
> +    }
Os autores e categorias instanciados estáticos são os salvos no repositório que são utilizados na bateria de testes para as outras funções, para esse, em especial, é necessário que seja na mão para garantir que tanto o Autor, quanto a Categoria não estão salvos nele

2020-08-26 19:10 UTC, geovaniggr commented on src/test/java/br/com/alura/edigi/controller/BookControllerTest.java
> +    }
Corrigi :heavy_check_mark:

2020-08-26 19:13 UTC, geovaniggr commented on src/test/java/br/com/alura/edigi/respository/AuthorRepositoryTest.java
> +        System.out.println(author);
Removi essa parte, porém é isso mesmo, o `save` do author repository tem apenas 2 comportamentos: Salvar com sucesso (void) ou lançar exceção, então aqui o Junit  passa no teste se tudo fluir bem, caso ocorra uma exceção o teste falha

2020-08-26 19:14 UTC, geovaniggr commented
Opa Wands, agora que consegui terminar o projeto Java e me organizar vou voltar a fazer os PR's com frequeência!

2020-08-26 20:44 UTC, wandersonmaceds approved these changes
Boa!

2020-08-26 20:44 UTC, wandersonmaceds commented on src/test/java/br/com/alura/edigi/respository/AuthorRepositoryTest.java
> +    @DisplayName("Autor não existente deve ser cadastrado sem falso negativo")
Acho que deixar a mensagem "sem falso negativo", me leva a investigar qual é o caso do falso negativo, como é um cadastro simples, eu removeria essa parte.

2020-08-26 22:15 UTC, merged