Penúltimo Card: Transformando de Memória para JDBC
geovaniggr/livraria-edigi pull request #7
Opened 2020-09-25 23:17 UTC by geovaniggr

2020-09-29 11:02 UTC, wandersonmaceds requested changes

2020-09-29 11:02 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/repository/AuthorRepository.java
> +            throw new IllegalArgumentException("Houve um erro! Provávelmente este email já esta cadastrado");
Aqui você tá quebrando um dos pilares de código: *Não usamos exception para controle de fluxo*. Acho que se a ideia é que o método retorna um boleano, ele não deve lançar exceptions, como você já tem o stacktrace printado ali, retorna false e pronto.

2020-09-29 11:02 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/repository/BookRepository.java
> +           throw new IllegalArgumentException("Houve um erro!. Já existe livro cadastrado com esse ISBN ou titulo");
*Não usamos exception para controle de fluxo*, mesmo comentário anterior.

2020-09-29 11:02 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/repository/CategoryRepository.java
> +            statement.setObject(2, category.getCreatedAt());
Aqui você poderia usar o timestamp, o LocalDateTime tem um método de conversão.

2020-09-29 11:02 UTC, wandersonmaceds commented on src/main/resources/schema.sql
> +    created_at timestamp NOT NULL
aqui você poderia delegar também pro banco a responsabilidade de criar a data (default now).

2020-09-29 14:43 UTC, geovaniggr commented on src/main/java/br/com/alura/edigi/repository/AuthorRepository.java
> +            throw new IllegalArgumentException("Houve um erro! Provávelmente este email já esta cadastrado");
Opa beleza, eu tinha pensando em deixar com retorno booleano, mas pensei que iria ir contra o primeiro card que pede para lançar exceção, mas é o que faz mais sentido mesmo!

2020-09-29 18:05 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/repository/AuthorRepository.java
> +            throw new IllegalArgumentException("Houve um erro! Provávelmente este email já esta cadastrado");
Sim, nesse caso não seria IllegalArgument, mas Runtime mesmo, não dá pra prever qual foi o problema, por isso sua mensagem diz que provavelmente foi isso.

2020-10-01 13:27 UTC, wandersonmaceds requested changes

2020-10-01 13:27 UTC, wandersonmaceds commented on src/main/java/br/com/alura/edigi/repository/AuthorRepository.java
Aqui eu tenho uma questão, depois de salvar o autor e retornar true, eu vou ter como estado do objeto o Id e o createdAt como null, correto? Deveria ficar assim?

2020-10-01 14:03 UTC, geovaniggr commented on src/main/java/br/com/alura/edigi/repository/AuthorRepository.java
Peguei seu ponto, no caso ficaria nulo apenas o `created_at` pois o identificador tanto do Autor, quanto da categoria são atributos já existentes e passados pelo usuário, mas num exemplo ( supondo que dentro do autor houvesse um `Long id`)

````
var author = new Author(....);
var book = new Book(...);

authorRepository.save(author);

bookRepository.save(book);
```
Por conta de não atualizar o estado do objeto tomaria um erro pois não haveria identificador único, sendo que neste momento teoricamente já é pra existir

Vou corrigir!

2020-10-01 17:55 UTC, wandersonmaceds approved these changes

2020-10-01 22:05 UTC, merged